name: API Testing Playwright

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  run_tests:
    runs-on: ubuntu-latest
    uses: gothinkster/realworld/.github/workflows/node-setup.yaml@main
    steps:
      - name: run tests
        run: npx nx e2e api-testing-playwright
