name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: gothinkster/realworld/.github/workflows/node-setup.yaml@main
      - name: Check prettier
        run: npm run prettier:check
      - name: Check ESLinter
        run: npm run lint:check
  unit_testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: gothinkster/realworld/.github/workflows/node-setup.yaml@main
      - name: Check unit tests
        run: npm run test --ci --lastCommit --maxWorkers=50%
