name: Create codebase diagram
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed
jobs:
  get_data:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: 'ignore,.github'
