name: test-documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --progress=false
      - name: Build production bundle
        run: npx nx build documentation
